kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Opt in to a local SKIE checkout with:
# ./gradlew -Pskie.useLocal=true -Pskie.localPath=/Users/sunset/HS_APP/SKIE ...
skie.useLocal=false
skie.localPath=/Users/sunset/HS_APP/SKIE
org.gradle.configuration-cache=true
